version = "1.0"

[metadata]
benchmark = "peng-weihan/SWE-QA-Bench"
benchmark_revision = "c13deac7a0d99b0ca2e593e004c4739475785b08"
task_id = "astropy:36"
source_index = 36
index_base = 0
role = "category"
category = "where"
question_type = "where"
question_hash = "6c758d177670ceb23d729afcf3171d970369293b9abb12001cbf44a7ec02a5c6"
repository = "astropy/astropy"
repository_commit = "0a041d38fbd0014298d4cf340d9f891c4522093f"

[verifier]
timeout_sec = 60.0

[agent]
timeout_sec = 1800.0

[environment]
build_timeout_sec = 1200.0
