version = "1.0"

[metadata]
benchmark = "peng-weihan/SWE-QA-Bench"
benchmark_revision = "c13deac7a0d99b0ca2e593e004c4739475785b08"
task_id = "flask:5"
source_index = 5
index_base = 0
role = "category"
category = "what"
question_type = "what"
question_hash = "fa7cca6ead96e85db1daff714af47cb8f1eb233e7455bce69f10ebb329471810"
repository = "pallets/flask"
repository_commit = "85c5d93cbd049c4bd0679c36fd1ddcae8c37b642"

[verifier]
timeout_sec = 60.0

[agent]
timeout_sec = 1800.0

[environment]
build_timeout_sec = 1200.0
